### ISSUE TITLE
Respect pretty linebreaks in eval

### ISSUE THREAD

**Issue by drautzburg** [kosmikus/lhs2tex#41]
When inserting ghci output in the document, linebreaks from ghci output are ignored. Often this is not a problem, but when you use a pretty printer to show a complex data structure, this behavior of lhs2tex renders the pretty printer useless.

**Comment by kosmikus** [comment]
Linebreaks by GHCi are rather random, and have little to do with how you want your document formatted. The proper way is to use `\perform` rather than `\eval`. The output of `\perform` can contain TeX commands, so you can write your own Haskell code that'll insert line-breaks exactly where you want them.
